### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by declan727** [EatMoreChicken/ta-plex-monitoring#1]
After I install the app in Splunk when I go to it I am getting a "500 internal server error" any thoughts?

I am getting this message:

Oops.
An error occurred while reading the page template. See web_service.log for more details

**Comment by EatMoreChicken** [comment]
Hi @declan727 ! Thank you for bringing this up to my attention. Did this only occur once after the initial install? After you went back to you Splunk home page, were you able to navigate to the app normally?

**Comment by declan727** [comment]
I am able to navigate the app normally but it looks like it has an issue with viewing the template in the app because the input or the configuration tab is giving me the issue so I have not been able to configure the app to try it out. sorry for the delay.

**Comment by declan727** [comment]
I believe there is an issue in the configuration.xml and the inputs.xml files in the ta-plex-monitoring/default/data/ui/views folder. I or possibly think there is code or something missing from the plex-monitoring/appserver/templates/base.html file. I hope this helps let me know if you want me to test anything in my Splunk / Plex environment.

**Comment by EatMoreChicken** [comment]
Hi again @declan727 , I was able to do a clean install and didn't encounter any errors during the process. Could you send me a cleaned snippet out of `web_service.log` for me to take a look at?

**Comment by EatMoreChicken** [comment]
Spoke with @declan727 . This ended up being an issue due to the app being downloaded as a `.zip` instead of the `.tar.gz` from the releases page. The app should be installed using the `.tar.gz` so that the permissions are preserved. The `.zip` from GitHub will cause permission issues for the files.

I updated the `README.md` to specify this.
